version: '2'

services:
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/html/public
      - ./app/static:/var/www/html/app/static/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./logs/nginx:/var/log/nginx
    links:
      - phalcon

  db:
    build: ./db
    restart: always
    ports:
            - "3307:3306"
    environment:
            - MYSQL_ROOT_PASSWORD=123456
            - MYSQL_DATABASE=internship
            - MYSQL_USER=root
            - MYSQL_PASSWORD=123456

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8060:8080
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 123456

  phalcon:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    restart: always
    ports:
    - "9000:9000"
    volumes:
    - ./:/var/www/html/
    - ./public:/var/www/html/public
    - ./vendor:/var/www/html/vendor
    - ./composer.json:/var/www/html/composer.json

  redis:
      image: redis:alpine
      restart: always
      links:
            - phalcon
